Class Test.SerialClass Extends %SerialObject
{

Storage Default
{
<Data name="SerialClassDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Test.SerialClassD</DataLocation>
<DefaultData>SerialClassDefaultData</DefaultData>
<IdLocation>^Test.SerialClassD</IdLocation>
<IndexLocation>^Test.SerialClassI</IndexLocation>
<StreamLocation>^Test.SerialClassS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
